import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";
import Header from "../components/common/header";
import Footer from "../components/common/footer";

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body className={`antialiased`}>
            <Header />
            {children}
            <Footer />
         </body>
      </html>
   );
}
