import NavbarLeft from "../components/page_components/admin/navbarleft";
import "../globals.css";
export const metadata = {
   title: "Next.js",
   description: "Generated by Next.js",
};

export default function RootLayout({
   children,
}: {
   children: React.ReactNode;
}) {
   return (
      <html lang="en">
         <body>
            <NavbarLeft />
            {children}
         </body>
      </html>
   );
}
